### ISSUE TITLE
How can i work double quotes?

### ISSUE THREAD

**Issue by coskunbaltaci** [voku/anti-xss-twig#1]
Hi!

I have a problem. Only did not work single quotes and double quotes. So why didn't it work for double quotes? 

Do you have any suggest?

{{ 'Hello, i try to <script>alert('Hack');</script> your site" ads="onClick();" 555-666-0606" K696=TobD([!+!]) ody="' | xss_clean }}

http://prntscr.com/h5pi0o

**Comment by voku** [comment]
Hi, can you please explain the problem a bit further?

PS: I have added a test here: https://github.com/voku/anti-xss-twig/commit/f27c2b07dc90fa77bee8ce570cec574189d6f94e

**Comment by voku** [comment]
use {% xss_clean %}YOUR CONTENT HERE{% end_xss_clean %}, this is working much better then the function-style via "| xss_clean
